name: Deploy to Beget via FTPS

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  web-deploy:
    name: FTPS Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Всё из public/ → корень сайта на Beget (public_html)
          local-dir: ./public/
          server-dir: ./
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/config.php
            **/config.local.php
